### ISSUE TITLE
Converting from Narrow StructArray to Arrow RecordBatch results in inconsistent nullability of column

### ISSUE THREAD

**Issue by johanpel** [mbrobbel/narrow#194]
Given the following test:

```rust
use arrow_array::RecordBatch;
use narrow::ArrayType;

#[derive(ArrayType)]
struct Test {
    test: Option<i32>,
}

#[test]
fn test() {
    let batch: RecordBatch = [Test { test: Some(1) }]
        .into_iter()
        .collect::<narrow::array::StructArray<Test>>()
        .into();

    assert!(batch.schema().field(0).is_nullable());
    assert!(batch.column(0).is_nullable());
}
```

it fails with:

```
assertion failed: batch.column(0).is_nullable()
```

so it looks like there may be a bug in the way the column is generated.

It passes when using this as input:
```rust
[Test { test: Some(1) }, Test { test: None }]
```

**Comment by mbrobbel** [comment]
The docs for that function (https://docs.rs/arrow/latest/arrow/array/trait.Array.html#method.is_nullable):

> Returns false if the array is guaranteed to not contain any logical nulls
> In general this will be equivalent to Array::null_count() != 0 but may differ in the presence of logical nullability, see [Array::logical_nulls](https://docs.rs/arrow/latest/arrow/array/trait.Array.html#method.logical_nulls).
> Implementations will return true unless they can cheaply prove no logical nulls are present. For example a [DictionaryArray](https://docs.rs/arrow/latest/arrow/array/struct.DictionaryArray.html) with nullable values will still return true, even if the nulls present in [DictionaryArray::values](https://docs.rs/arrow/latest/arrow/array/struct.DictionaryArray.html#method.values) are not referenced by any key, and therefore would not appear in [Array::logical_nulls](https://docs.rs/arrow/latest/arrow/array/trait.Array.html#method.logical_nulls).

So this is checking the null count of that array, which is 0 in the given example. 

The field method (https://docs.rs/arrow/latest/arrow/datatypes/struct.Field.html#method.is_nullable):
> Indicates whether this [Field](https://docs.rs/arrow/latest/arrow/datatypes/struct.Field.html) supports null values.

Which seems to return the correct value for both test cases.

**Comment by johanpel** [comment]
I see, that is quite confusing, but thanks for clarifying.
