### ISSUE TITLE
Support for bstr

### ISSUE THREAD

**Issue by v1gnesh** [mbrobbel/narrow#229]
In theory, I think it's straightforward to add support for `bstr` types (`BStr` and `BString`), as they implement `fmt::Debug` and `fmt::Display`. And via `narrow`, they can become `StringView`.

Is this something you could consider, please?
I might have to create a fork of `bstr` as I'm working with byte strings, but need to insert a codepage conversion step before I rely on `bstr`'s UTF8 machinery.

**Comment by mbrobbel** [comment]
We can just store these in variable size binary arrays.

**Comment by v1gnesh** [comment]
That won't give a string on the other side (arrow data type) though, right?

**Comment by mbrobbel** [comment]
No it will just be bytes. For strings Arrow requires guaranteed valid UTF-8 encoding.

**Comment by v1gnesh** [comment]
Right, if I know in my input that those bytes are valid UTF8, and don't want to do `String::from_utf8()` (therefore bstr), I can't then output to Arrow String type, if it converts to binary array.

**Comment by v1gnesh** [comment]
I am using this currently. Just thinking through options to avoid unsafe :)
Knowing my source will be valid, I guess this will be fine.
Thanks again for narrow and for your continued work on this (as & when you find time).
Much much needed bit of software :heart:

**Comment by mbrobbel** [comment]
> to avoid unsafe

If you can guarantee that your bytes are valid `UTF-8` you can skip the check and use `unsafe`.

> I guess this will be fine

However, if you are not, you should check to make sure the bytes contain valid `UTF-8`. Which is why we can't put `bstr` items in `UTF-8` arrays.
