### ISSUE TITLE
Implement `IntoIterator` for `Offset` and `StringArray`

### ISSUE THREAD

**Issue by dhruv9vats** [mbrobbel/narrow#57]
Opening an issue to discuss and understand what this implementation would look like.

Is it correct to think that the `Offset` struct operates in the `u8` realm? And the `IntoIterator` implementation for a `StringArray` with the `type Item = String` will have to deal with the complexity of converting the iterator of `u8`'s the wrapped `Offset` produces into a `String` type using the offset values provided by `offset_buffer()`?

Pardon if I'm overlooking something obvious.

**Comment by mbrobbel** [comment]
`Offset` does not restrict the [data](https://github.com/mbrobbel/narrow/blob/main/src/offset/mod.rs#L46) it wraps around, however to construct it from an iterator over `T`, `T` must implement `IntoIterator + Length`. If you look at the tests of the `iter` mod in the `offset` mod [here](https://github.com/mbrobbel/narrow/blob/main/src/offset/iter.rs#LL168-L206C2), you can see that there are some example iterators for the `Offset` wrapper.

However, for the `IntoIterator` of `StringArray` we need a new `Offset` iterator that just yields the lengths (via the offset buffer). Then the `StringArray` iterator can wrap around that and use the underlying data (`u8` buffer) to yield `str` slices (via https://doc.rust-lang.org/stable/std/str/fn.from_utf8_unchecked.html).
